"""Materialize the offline, abstract-verified v1 research cards.

This script reads no network or competition data. Paper mechanisms are
paraphrases of the linked abstracts; diagnostic relevance is curator inference.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from connectome.research_foundation import validate_card
from connectome.research_retrieval import load_library


DEST = ROOT / "competition_engineering/research_cards/v1"
VERIFIED_ON = "2026-09-30"
LICENSE_NOTE = "Metadata and curator paraphrase only; verify paper license before reusing paper text."

# id, family, title, authors, year, URL, mechanism, useful_when, diagnostic
# signature, causality/incremental caveat, CPU caveat, limitation.
SOURCES = [
    ("gated_recurrence_gru", "recurrence", "Empirical Evaluation of Gated Recurrent Neural Networks on Sequence Modeling", ["Junyoung Chung", "Caglar Gulcehre", "KyungHyun Cho", "Yoshua Bengio"], 2014, "https://arxiv.org/abs/1412.3555", "GRU and LSTM gates regulate recurrent state; the paper compares gated units with simpler recurrence.", "Curator inference: persistent temporal errors may indicate inadequate learned state.", "Long-lag residual persistence or sequence-dependent errors.", "Use a forward-only state and reset it at each sequence boundary.", "Dense recurrent matrices are paid for on every callback row.", "Comparable GRU and LSTM results in the paper do not imply a gain on this task."),
    ("lstm_memory", "recurrence", "Long Short-Term Memory", ["Sepp Hochreiter", "Jürgen Schmidhuber"], 1997, "https://doi.org/10.1162/neco.1997.9.8.1735", "Memory cells and gates address difficult long-range gradient propagation in recurrent learning.", "Curator inference: a longer effective memory may explain slow residual decay.", "Residual persistence across long sequence lags.", "Use only preceding inputs and reset hidden and cell states between sequences.", "Multiple gates add row-wise CPU matrix operations.", "Long-memory motivation does not establish that larger recurrence is necessary here."),
    ("dilated_recurrence", "recurrence", "Dilated Recurrent Neural Networks", ["Shiyu Chang", "Yang Zhang", "Wei Han"], 2017, "https://arxiv.org/abs/1710.02224", "Multi-resolution recurrent skip connections shorten paths across long sequences.", "Curator inference: lag-specific errors may benefit from distinct temporal scales.", "Residual structure at separated fixed lags.", "Maintain only past states for each dilation and reset all rings per sequence.", "Multiple state buffers and recurrent updates increase callback cost.", "The reported long-dependency tasks differ from this competition."),
    ("residual_connections", "residual", "Deep Residual Learning for Image Recognition", ["Kaiming He", "Xiangyu Zhang", "Shaoqing Ren", "Jian Sun"], 2015, "https://arxiv.org/abs/1512.03385", "Residual blocks learn adjustments relative to their inputs, easing optimization of deeper networks.", "Curator inference: a strong base model with structured remaining error may admit a bounded correction.", "Root-to-candidate improvements with a coherent residual left over.", "A correction must use the causal base prediction and available past/current features only.", "An extra correction model adds CPU inference cost.", "The paper studies image classification, not causal regression correction."),
    ("basis_residual_forecasting", "residual", "N-BEATS: Neural basis expansion analysis for interpretable time series forecasting", ["Boris N. Oreshkin", "Dmitri Carpov", "Nicolas Chapados", "Yoshua Bengio"], 2019, "https://arxiv.org/abs/1905.10437", "Stacked fully connected blocks use backward and forward residual links for forecasting.", "Curator inference: several separable temporal components may remain after a baseline.", "Distinct position or magnitude error patterns across sequences.", "A Connectome adaptation needs an explicit causal window and incremental cache.", "A deep stack can exceed per-row CPU limits without careful deployment.", "Original results concern univariate forecasts and do not transfer automatically."),
    ("generic_tcn", "convolution", "An Empirical Evaluation of Generic Convolutional and Recurrent Networks for Sequence Modeling", ["Shaojie Bai", "J. Zico Kolter", "Vladlen Koltun"], 2018, "https://arxiv.org/abs/1803.01271", "The paper evaluates a simple convolutional sequence architecture against recurrent baselines and reports longer effective memory on its benchmarks.", "Curator inference: fixed-lag dependence may be expressible with a finite receptive field.", "Residual persistence within a bounded lag window.", "Use left-padded causal convolutions and cache only past activations.", "Full-window recomputation may be too slow per row; measure incremental execution.", "Past local TCN experiments here are search evidence and should not be overwritten by external benchmarks."),
    ("dilated_causal_convolution", "convolution", "WaveNet: A Generative Model for Raw Audio", ["Aaron van den Oord", "Sander Dieleman", "Heiga Zen"], 2016, "https://arxiv.org/abs/1609.03499", "An autoregressive network conditions each output on preceding audio samples.", "Curator inference: repeated fixed-lag effects may fit a bounded causal convolution stack.", "Several stable residual-persistence lags.", "Apply causal left padding and stateful history buffers; never center the kernel.", "Dilated history can be cached, but a naive full receptive-field pass is costly.", "Audio-generation evidence does not establish Connectome WP improvement."),
    ("gated_convolution", "convolution", "Language Modeling with Gated Convolutional Networks", ["Yann N. Dauphin", "Angela Fan", "Michael Auli", "David Grangier"], 2016, "https://arxiv.org/abs/1612.08083", "A finite-context gated convolution can model sequences while allowing parallel training.", "Curator inference: short-to-medium nonlinear lag interactions may need input-dependent gating.", "Feature-residual relationships that vary with recent context.", "Use past-only convolution state and deterministic sequence resets.", "Gate and convolution work must be benchmarked as CPU callback operations.", "Its language-model latency comparison is not a deployment guarantee here."),
    ("structured_state_space", "state_space", "Efficiently Modeling Long Sequences with Structured State Spaces", ["Albert Gu", "Karan Goel", "Christopher Ré"], 2021, "https://arxiv.org/abs/2111.00396", "S4 parameterizes state-space dynamics to model long sequences efficiently.", "Curator inference: broad lag persistence may suggest a compact dynamical state.", "Slow residual decay across multiple fixed lags.", "Use the recurrent causal state update, not a future-aware sequence convolution.", "Kernel efficiency in training does not imply cheap one-row CPU inference.", "Published long-sequence benchmark gains do not predict local WP."),
    ("selective_state_space", "state_space", "Mamba: Linear-Time Sequence Modeling with Selective State Spaces", ["Albert Gu", "Tri Dao"], 2023, "https://arxiv.org/abs/2312.00752", "Input-dependent state-space parameters selectively propagate or forget information.", "Curator inference: residual persistence conditional on current features may call for selective memory.", "Lagged feature-residual structure with context-dependent persistence.", "Run a forward-only selective recurrent update and reset its state per sequence.", "Specialized kernels in the paper may not map to affordable CPU callbacks.", "Its results are on other modalities and should not dominate simpler mechanisms."),
    ("online_polynomial_memory", "state_space", "HiPPO: Recurrent Memory with Optimal Polynomial Projections", ["Albert Gu", "Tri Dao", "Stefano Ermon"], 2020, "https://arxiv.org/abs/2008.07669", "HiPPO incrementally compresses signal history using polynomial projections.", "Curator inference: multi-scale error may call for compact online history summaries.", "Residual dependence spanning both short and long fixed lags.", "Update coefficients with current/past inputs only and clear state at reset.", "State update width sets CPU cost and memory footprint.", "Compression quality depends on assumptions about past-time weighting."),
    ("liquid_time_constant", "state_space", "Liquid Time-constant Networks", ["Ramin Hasani", "Mathias Lechner", "Alexander Amini", "Daniela Rus", "Radu Grosu"], 2020, "https://arxiv.org/abs/2006.04439", "Gated first-order dynamical systems have state-dependent time constants.", "Curator inference: apparent memory timescale may vary with observed regime.", "Sequence-specific or feature-dependent residual persistence.", "Integrate forward in time with a deterministic state reset.", "Numerical solver overhead may be unacceptable for per-row CPU inference.", "The paper's time-series results do not establish feasibility under this callback budget."),
    ("ridge_regularization", "simple_models", "Ridge Regression: Biased Estimation for Nonorthogonal Problems", ["Arthur E. Hoerl", "Robert W. Kennard"], 1970, "https://doi.org/10.1080/00401706.1970.10488634", "Biased shrinkage stabilizes regression coefficients when predictors are nonorthogonal.", "Curator inference: correlated lagged features can make an unregularized correction unstable.", "Strong feature-residual relationships with unstable per-sequence gains.", "Use only causal feature values available at prediction time.", "A fixed linear transform is usually cheap on CPU, subject to feature count.", "Global linear effects cannot express all conditional or long-memory errors."),
    ("linear_forecast_baseline", "simple_models", "Are Transformers Effective for Time Series Forecasting?", ["Ailing Zeng", "Muxi Chen", "Lei Zhang", "Qiang Xu"], 2022, "https://arxiv.org/abs/2205.13504", "The paper tests simple one-layer linear forecasting baselines against complex transformers.", "Curator inference: complexity should be justified by a diagnostic gain over linear corrections.", "Stable current/lagged feature-residual relationships.", "Use strictly trailing input windows for a causal adaptation.", "Linear heads can be inexpensive; window extraction still has a cost.", "Published comparisons target long-term forecasting benchmarks, not this scoring rule."),
    ("hierarchical_reservoir", "reservoir", "Deep-ESN: A Multiple Projection-encoding Hierarchical Reservoir Computing Framework", ["Qianli Ma", "Lifeng Shen", "Garrison W. Cottrell"], 2017, "https://arxiv.org/abs/1711.05255", "Hierarchical echo-state reservoirs and projections are used to represent multiscale time series.", "Curator inference: fixed random recurrent features may test a temporal hypothesis cheaply.", "Residual patterns at multiple timescales with limited training budget.", "Use input-only reservoir updates and reset all reservoir states per sequence.", "Reservoir width can dominate CPU matrix-vector time despite cheap fitting.", "Echo-state stability and useful timescales require explicit checking."),
    ("causal_self_attention", "attention", "Attention Is All You Need", ["Ashish Vaswani", "Noam Shazeer", "Niki Parmar"], 2017, "https://arxiv.org/abs/1706.03762", "The Transformer uses attention in place of recurrence and convolution for sequence modeling.", "Curator inference: content-dependent relationships across a bounded past window may matter.", "Lagged feature-residual signal that differs by current content.", "Mask every future position and use a past-only cache at inference.", "Per-row attention over long history can be expensive on CPU.", "Its machine-translation training advantages are not evidence of Connectome benefit."),
    ("sparse_long_attention", "attention", "Informer: Beyond Efficient Transformer for Long Sequence Time-Series Forecasting", ["Haoyi Zhou", "Shanghang Zhang", "Jieqi Peng"], 2020, "https://arxiv.org/abs/2012.07436", "Informer introduces sparse attention and distilling for long-sequence forecasting.", "Curator inference: very long input history might need a selective context mechanism.", "Long-lag residual errors not explained by compact state summaries.", "Replace the original forecast decoder with a strictly causal callback design.", "Sparse training complexity does not guarantee fast single-step CPU inference.", "Original architecture predicts future sequences in one operation, unlike this callback."),
    ("patch_attention", "attention", "A Time Series is Worth 64 Words: Long-term Forecasting with Transformers", ["Yuqi Nie", "Nam H. Nguyen", "Phanwadee Sinthong", "Jayant Kalagnanam"], 2022, "https://arxiv.org/abs/2211.14730", "PatchTST segments time series into patches and shares a channel-independent transformer.", "Curator inference: coarse history summaries may retain lag information at lower attention cost.", "Broad long-lag structure across multiple feature channels.", "Build patches only from available past/current observations.", "Patch updates and attention cache still require CPU timing.", "Long-term forecast benchmarks differ from online one-row prediction."),
    ("decomposition_attention", "attention", "Autoformer: Decomposition Transformers with Auto-Correlation for Long-Term Series Forecasting", ["Haixu Wu", "Jiehui Xu", "Jianmin Wang", "Mingsheng Long"], 2021, "https://arxiv.org/abs/2106.13008", "Progressive decomposition and auto-correlation model recurring sub-series patterns.", "Curator inference: consistent multi-lag residual structure may indicate repeated components.", "Repeated persistence peaks or position-specific periodic structure.", "Any decomposition window must be trailing and available at callback time.", "Decomposition and attention may be costly per row.", "Original long-horizon forecasting setup is not directly deployable here."),
    ("sparse_expert_gating", "gating", "Outrageously Large Neural Networks: The Sparsely-Gated Mixture-of-Experts Layer", ["Noam Shazeer", "Azalia Mirhoseini", "Krzysztof Maziarz"], 2017, "https://arxiv.org/abs/1701.06538", "A trainable gate selects a sparse subset of feed-forward experts per example.", "Curator inference: distinct feature regimes could merit specialized corrections.", "Opposite residual bias or magnitude effects across fixed groups.", "Gate and experts must use only current/past features.", "Sparse expert count does not guarantee low CPU dispatch overhead.", "The published very-large-scale setting is far from this deployment budget."),
    ("featurewise_nonlinear", "nonlinear_correction", "Neural Additive Models: Interpretable Machine Learning with Neural Nets", ["Rishabh Agarwal", "Levi Melnick", "Nicholas Frosst"], 2020, "https://arxiv.org/abs/2004.13912", "A learned sum of per-feature neural functions captures nonlinear univariate effects.", "Curator inference: nonlinear feature-residual relations may need more than linear correction.", "Persistent magnitude or feature-group residual structure after linear fitting.", "Per-feature functions must depend on available features only.", "Many feature networks can add substantial callback overhead.", "Featurewise additivity omits interactions unless explicitly extended."),
    ("classification_temperature_scaling", "calibration", "On Calibration of Modern Neural Networks", ["Chuan Guo", "Geoff Pleiss", "Yu Sun", "Kilian Q. Weinberger"], 2017, "https://arxiv.org/abs/1706.04599", "The paper studies post-hoc calibration of classification confidence and finds temperature scaling effective on its datasets.", "Curator inference: a residual scale pattern can motivate checking a low-cost output transform.", "Systematic prediction-scale mismatch by target or magnitude.", "Fit only on designated training data; inference needs only the current prediction.", "A scalar transform is cheap on CPU.", "Classification probability calibration is not the same objective as weighted Pearson regression."),
    ("causal_instance_normalization", "calibration", "Reversible Instance Normalization for Accurate Time-Series Forecasting Against Distribution Shift", ["Taesung Kim", "Jinhee Kim", "Yunwon Tae", "Cheonbok Park", "Jang-Ho Choi", "Jaegul Choo"], 2022, "https://openreview.net/forum?id=cGDAkQo1C0p", "Reversible instance normalization removes and restores instance statistics for forecasting under distribution shift.", "Curator inference: input-statistic drift may explain sequence-position or magnitude errors.", "Systematic input scale or bias changes across sequences.", "For this callback, statistics must use a trailing window only; original full-window designs need adaptation.", "Maintain incremental moments to bound CPU row cost.", "Input normalization cannot use unseen future sequence statistics or future targets."),
]


def materialize() -> tuple[int, str]:
    DEST.mkdir(parents=True, exist_ok=True)
    if list(DEST.glob("*.json")):
        raise ValueError("refusing to overwrite an existing research library")
    for (card_id, family, title, authors, year, url, mechanism, useful_when,
         signatures, causality, cpu, limitation) in SOURCES:
        card = validate_card({
            "schema_version": 1, "card_id": card_id, "version": 1,
            "card_type": "paper", "family": family, "tags": [family, "causal-adaptation-required"],
            "title": title, "authors": authors, "year": year, "source_url": url,
            "source_locator": "Abstract", "curator": "Codex, primary abstract review",
            "verified_on": VERIFIED_ON, "claim_confidence": "limited",
            "mechanism": mechanism, "useful_when": useful_when,
            "diagnostic_signatures": "Curator inference: " + signatures,
            "assumptions": "Transfer to Connectome requires an independent search-only test.",
            "limitations": limitation, "causality": causality,
            "incremental_inference": causality, "training_compute": "Measure on the configured training tier.",
            "cpu_deployment": cpu, "dependencies": "Implementation-dependent; card retrieval uses only Python stdlib.",
            "licensing": LICENSE_NOTE,
            "concise_relevance": "Possible mechanism to evaluate against the fixed search atlas; no experiment is prescribed.",
        })
        (DEST / f"{card_id}.json").write_text(
            json.dumps(card, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8"
        )
    cards, digest = load_library(DEST)
    return len(cards), digest


if __name__ == "__main__":
    count, digest = materialize()
    print(f"cards={count} manifest_sha256={digest}")
